import java.io.IOException;

import java.net.UnknownHostException;
import java.util.ArrayList;


import Model.beijing;

/*
 * captian1.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class captian1 extends javax.swing.JFrame {

	/** Creates new form captian1 */
	public captian1() {
		initComponents();
		this.setLocationRelativeTo(null);
		try {
			load1();
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	void load() throws UnknownHostException, IOException,
			ClassNotFoundException {
		beijing u = new beijing();
		ArrayList<beijing> beijings = u.viewData();
		Object detail[][] = new Object[beijings.size()][1];
		int i;
		String e;
		e = this.jTextField2.getText();
		i = Integer.parseInt(e);
		if (i < 4) {
			int a;
			String b;
			String c;
			String d;
			b = this.jTextField1.getText();
			a = Integer.parseInt(b);
			this.jTextArea1.setText(beijings.get(a).getContent());
			a = a + 1;
			c = String.valueOf(a);
			this.jTextField1.setText(c);
			i = i + 1;
			d = String.valueOf(i);
			this.jTextField2.setText(d);
		} else {
			new captian4().setVisible(true);
			this.dispose();
		}
	}

	void load1() throws UnknownHostException, IOException,
			ClassNotFoundException {
		beijing u = new beijing();
		ArrayList<beijing> beijings = u.viewData();
		Object detail[][] = new Object[beijings.size()][1];
		for (int i = beijings.size() - 1; i < beijings.size(); i++) {
			this.jTextArea1.setText(beijings.get(i - 4).getContent());
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField2 = new javax.swing.JTextField();
		jTextField1 = new javax.swing.JTextField();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jTextField2.setText("1");

		jTextField1.setText("1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));

		jButton2.setBackground(new java.awt.Color(0, 0, 0));
		jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton2.setForeground(new java.awt.Color(204, 0, 0));
		jButton2.setText("\u8df3\u8fc7");
		jButton2.setBorder(null);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBounds(20, 510, 49, 33);
		jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jButton1.setBackground(new java.awt.Color(0, 0, 0));
		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton1.setForeground(new java.awt.Color(204, 0, 0));
		jButton1.setText("Next");
		jButton1.setBorder(null);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBounds(380, 510, 55, 33);
		jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/1.jpg"))); // NOI18N
		jLabel1.setBounds(0, 0, 460, 190);
		jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

		jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setFont(new java.awt.Font("ËÎÌו", 0, 18));
		jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1.setEnabled(false);
		jScrollPane1.setViewportView(jTextArea1);

		jScrollPane1.setBounds(0, 190, 460, 370);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new captain17().setVisible(true);
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			load();
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new captian1().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}